# Generated by Django 4.2.13 on 2026-05-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('RESPONSE_BREACH', 'Breach délai de réponse'), ('RESOLUTION_BREACH', 'Breach délai de résolution'), ('PRIORITY_CHANGE', 'Changement de priorité P1/P2'), ('UNASSIGNED_TIMEOUT', 'Non assigné après délai')], max_length=30)),
                ('priority', models.CharField(blank=True, help_text='Laisser vide = toutes priorités', max_length=2)),
                ('notify_via', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'Notification in-app'), ('BOTH', 'Email + In-app')], default='BOTH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_targets', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire escalade')),
            ],
            options={
                'verbose_name': "Règle d'escalade",
                'verbose_name_plural': "Règles d'escalade",
            },
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('notified', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_escalations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escalation.escalationrule')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='tickets.ticket')),
            ],
            options={
                'verbose_name': "Événement d'escalade",
                'verbose_name_plural': "Événements d'escalade",
                'ordering': ['-sent_at'],
            },
        ),
    ]
