# Generated by Django 4.2.13 on 2026-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P1', 'P1 — Critique'), ('P2', 'P2 — Élevée'), ('P3', 'P3 — Normale'), ('P4', 'P4 — Basse')], max_length=2, unique=True)),
                ('response_time', models.PositiveIntegerField(help_text='Délai de 1ère réponse (minutes)')),
                ('resolution_time', models.PositiveIntegerField(help_text='Délai de résolution (minutes)')),
                ('business_hours', models.BooleanField(default=True, help_text='Calculer en heures ouvrées seulement')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Politique SLA',
                'verbose_name_plural': 'Politiques SLA',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='SLATracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_due', models.DateTimeField(blank=True, null=True)),
                ('resolution_due', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_breached', models.BooleanField(default=False)),
                ('resolution_breached', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sla.slapolicy')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracker', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Suivi SLA',
                'verbose_name_plural': 'Suivis SLA',
            },
        ),
    ]
